### ISSUE TITLE
Assign automatic cherry-picked issue to 

### ISSUE THREAD

**Issue by SunRunAway** [pingcap-incubator/cherry-bot#10]
After a PR is cherry-picked by bot, the cherry-picked PR should have an assignee.

bot has been cherry-picked lots of PRs https://github.com/pingcap/tidb/pulls/sre-bot, but we cannot tracker the owner of these.

If the author of the original PR is a contributor, the cherry-picked PR should be assigned to the last reviewer.
If the author of the original PR is a member, the cherry-picked PR should be assigned to the member.

**Comment by zz-jason** [comment]
@you06 PTAL

**Comment by you06** [comment]
There should be a configuration field for this.

**Comment by SunRunAway** [comment]
friendly ping @you06

**Comment by SunRunAway** [comment]
Another friendly ping @you06
