### ISSUE TITLE
Should not remove existing label

### ISSUE THREAD

**Issue by hi-rustin** [pingcap-incubator/cherry-bot#39]
## Bug Report

- [x] I have searched the [issues](https://github.com/pingcap-incubator/cherry-bot/issues) of this repository and believe that this is not a duplicate.

### Related link

- Which project: TiDB

- PR or Issue Link: https://github.com/pingcap/tidb/pull/18217

### Steps to reproduce(Optional)
1. Add label LGT2(not approve,just add label)
2. Approve PR

### What is expected?
It should not remove existing label LGT2.

### What is actually happening?
It removed label LGT2.

**Comment by you06** [comment]
I guess this is caused by latest changes, @AndreMouche is this as expected?
